### ISSUE TITLE
Goverlay Can't Launch, Coredumps (using latest -git OR -bin package on Arch)

### ISSUE THREAD

**Issue by gardotd426** [benjamimgois/goverlay#159]
Installed goverlay, tried to launch it from the Plasma app launcher. Nothing happened. So I launch `goverlay` from the terminal, and I get:

```
[1]    608054 abort (core dumped)  QT_QPA_PLATFORM=xcb mangohud --dlsym goverlay --style fusion
```

So I check /usr/bin/goverlay, and I see it's just a script with `QT_QPA_PLATFORM=xcb mangohud --dlsym /usr/libexec/goverlay-bin --style fusion`.  I try running it without `QT_QPA_PLATFORM`, same crash. I try WITHOUT anything, just `/usr/libexec/goverlay-bin`, and it launches, but obviously MangoHud doesn't appear. 

This was with the `goverlay-git` package. So I installed `goverlay-bin`, which uses the same command in the .desktop file (`QT_QPA_PLATFORM=xcb mangohud --dlsym goverlay --style fusion`), and it also has the same exact issue:

```
[1]    608099 abort (core dumped)  mangohud --dlsym goverlay
```

Here's the output of `coredumpctl debug 608099` -> `backtrace`:

```
#0  0x00007fc567ce1d22 in raise () from /usr/lib/libc.so.6
#1  0x00007fc567ccb862 in abort () from /usr/lib/libc.so.6
#2  0x00007fc56323842c in ?? () from /usr/lib/qt/plugins/platforms/libdxcb.so
#3  0x00007fc568586e2e in call_init () from /lib64/ld-linux-x86-64.so.2
#4  0x00007fc568586f1c in _dl_init () from /lib64/ld-linux-x86-64.so.2
#5  0x00007fc567dddd45 in _dl_catch_exception () from /usr/lib/libc.so.6
#6  0x00007fc56858b20a in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#7  0x00007fc567dddce8 in _dl_catch_exception () from /usr/lib/libc.so.6
#8  0x00007fc56858a9bb in _dl_open () from /lib64/ld-linux-x86-64.so.2
#9  0x00007fc5683e236c in ?? () from /usr/lib/libdl.so.2
#10 0x00007fc567dddce8 in _dl_catch_exception () from /usr/lib/libc.so.6
#11 0x00007fc567ddddb3 in _dl_catch_error () from /usr/lib/libc.so.6
#12 0x00007fc5683e2b99 in ?? () from /usr/lib/libdl.so.2
#13 0x00007fc5683e23f8 in dlopen () from /usr/lib/libdl.so.2
#14 0x00007fc5667fc081 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007fc5667f5896 in ?? () from /usr/lib/libQt5Core.so.5
#16 0x00007fc5667f5e83 in ?? () from /usr/lib/libQt5Core.so.5
#17 0x00007fc5667f6218 in ?? () from /usr/lib/libQt5Core.so.5
#18 0x00007fc5667e98ae in QFactoryLoader::instance(int) const () from /usr/lib/libQt5Core.so.5
#19 0x00007fc566d632e4 in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) ()
   from /usr/lib/libQt5Gui.so.5
#20 0x00007fc566d74fc9 in QGuiApplicationPrivate::createPlatformIntegration() () from /usr/lib/libQt5Gui.so.5
#21 0x00007fc566d76661 in QGuiApplicationPrivate::createEventDispatcher() () from /usr/lib/libQt5Gui.so.5
#22 0x00007fc566807117 in QCoreApplicationPrivate::init() () from /usr/lib/libQt5Core.so.5
#23 0x00007fc566d79673 in QGuiApplicationPrivate::init() () from /usr/lib/libQt5Gui.so.5
#24 0x00007fc5674813ca in QApplicationPrivate::init() () from /usr/lib/libQt5Widgets.so.5
#25 0x00007fc5682c84c4 in QApplication_Create () from /usr/lib/libQt5Pas.so.1
#26 0x00000000005f7205 in ?? ()
#27 0x0000000000858f80 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--backtrace
#28 0x0000000000000000 in ?? ()
```

I'm on a completely up-to-date Arch Linux system. I've also tried with `mangohud-git` instead of the latest stable release.

**Comment by benjamimgois** [comment]
I'm investigating the issue, several people are reporting this issue. The strange thing is that it's working fine for me on a Manjaro unstable build.

**Comment by gardotd426** [comment]
Weirdly it started working after a system update (but no goverlay-related packages seem to have been updated). 

But now there's a new issue. Launching it from the included .desktop file causes this warning to immediately pop up:


![Screenshot_20211117_114730](https://user-images.githubusercontent.com/54234607/142244345-162f7bf8-24d3-4613-8065-262b85c73615.png)

This makes zero sense. None of my disks are full (not even close, really), and definitely not my ~/.config partition. Also when I launch from the terminal using the exact same command as the .desktop file, there's no warning:

 
![Screenshot_20211117_114933](https://user-images.githubusercontent.com/54234607/142244722-141f8438-5045-4bdb-881b-40ef70879033.png)

It doesn't even tell me what disk it thinks is full. And like I said there are no full disks. I have a separate partition for ~/.config that's 6.7GiB and it's only half full (3.3 GiB).

**Comment by Yaikava** [comment]
btw I have the same issue with the "Disk full" message on Fedora 35.

**Comment by benjamimgois** [comment]
> btw I have the same issue with the "Disk full" message on Fedora 35. (GOverlay version `0.6.4-1.fc35`)
> 
> Including this behavior: | Also when I launch from the terminal using the exact same command as the .desktop file, there's no warning:


This is really strange, i'm sure that message "disk full" doesn't come from goverlay (i haven't write any code related) but it might be trigerring that error in some way. Can you check if that happen in 0.6.3 ? I can't reproduce the issue here. Tomorrow i'll make a fresh install of fedora and opensuse tumbleweed, since the problem seems more recorrent with them.

**Comment by gardotd426** [comment]
It happens on 0.6.3 too.


As you can see, just to confirm I have nothing that's even over 90% full (~vfio2/Windows is my VFIO VM and so it's not relevant and even then it's only 91%). Most of the stuff that's even in the 70-80% full range are 1TB disks so we're talking 100-150GB of free space:

![Screenshot_20211117_202742](https://user-images.githubusercontent.com/54234607/142334314-9b1cff7d-7502-4d5d-b729-0b825b5ba61b.png)
![Screenshot_20211117_202810](https://user-images.githubusercontent.com/54234607/142334365-a3aae553-e388-4c70-9dea-19b303e43ee8.png)

**Comment by Slayer5934** [comment]
I'm getting the same "Disk Full." error on Manjaro KDE Plasma when launching through the start menu icon but running the command through terminal does not give the error.

**Comment by quasigod-io** [comment]
I'm currently unable to launch with the same line as the original issue. The same thing happens using goverlay, goverlay-bin, and goverlay-git. Running Arch and 5.15 Zen Kernel.
